config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/edit'

  root 'static_pages#home'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  resources :user_sessions  

  get 'goals/edit' => 'goals#edit'

  resources :users

  resources :lists do
    resources :goals do
      put 'complete', on: :collection
    end
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :list
  before_save :cap_first

  validates :content, presence: true

  after_initialize :init

  def complete
    self.done = true
    self.save
  end

  private

  	def init
  		self.done ||= false
  	end

  	def cap_first
  		self.content[0] = content[0].capitalize
  	end
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :goals, dependent: :destroy
	belongs_to :user

	validates :title, presence: true

	before_save :titleize_title

	private

		def titleize_title
			self.title = title.titleize
		end
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |config|
		config.crypto_provider = Authlogic::CryptoProviders::BCrypt
	end
	has_many :lists, dependent: :destroy
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  	def current_user_session
  		return @current_user_session if defined?(@current_user_session)
  		@current_user_session = UserSession.find
  	end

  	def current_user
  		return @current_user if defined?(@current_user)
  		@current_user = current_user_session && current_user_session.record
  	end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
  	@list = List.find(params[:list_id])
  	@goal = @list.goals.create(goal_params)
  	redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:list_id])
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to list_path(@list)
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes goal_params
      redirect_to list_path(params[:list_id])
    else
      render 404
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def complete
    @list = List.find(params[:list_id])
    Goal.where(id: params[:goal_ids]).update_all(:done => :true)
    redirect_to list_path(@list)
  end

  private

  	def goal_params
  		params.require(:goal).permit(:content, :done)
  	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists
  	@numrows = 1 + @lists.count / 3
  end

  def show
    @list = List.find(params[:id])
  end

  def new
  	@list = List.new
  end

  def create
  	@list = current_user.lists.create(list_params)
  	redirect_to lists_path  	
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to lists_path
    else
      flash[:danger] = "List could not be updated"
      render 'edit'
    end
  end

  def complete_goal
    @list = List.find(params[:id])

    @goal = @list.goals.find(params[:goal_id])

    if @goal.complete
      redirect_to list_path(@list)
    else
      render 404
    end
  end

  def destroy   
    @list = List.find(params[:id])
    @list.destroy 
    redirect_to lists_path
  end

  private

  	def list_params
  		params.require(:list).permit(:title)
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	def new
		@user_session = UserSession.new
	end

	def create
		@user_session = UserSession.new(params[:user_session])
		if @user_session.save
			flash[:notice] = "Successfully logged in."
			redirect_to lists_path
		else
			flash[:danger] = "Login was not successful."
			render 'new'
		end
	end

	def destroy
		@session = UserSession.find(params[:id])
		@session.destroy
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "Registration successful."
  		redirect_to lists_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		flash[:notice] = "Successfully updated user."
  		redirect_to lists_url
  	else
  		render 'edit'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:login, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_tag goals_edit_path(@goal) do %>
  
  <p>
    <%= label_tag :content %> <br>
    <%= text_field_tag :content %>
  </p> 

  <p>
    <%= submit_tag "Save Goal" %>
  </p>
<% end %>

<p>
  <%= link_to "Back", lists_path(@list) %>
</p>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<h1>Edit your subgoal</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toodoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="narrow">
		<%= render 'shared/header' %>
	</div>
	<div class="container narrow">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>
		<%= yield %>		
	</div>

	<div class="narrow">
		<%= render 'shared/footer' %>
	</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>

  <% if @list.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:
    
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p> 

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to "Back", lists_path %>
</p>

app/views/lists/edit.html.erb
<h1>Edit your list</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<h2>Your Goals</h2>

<br>

<% counter = 1 %>

<div class="row">

	<% @lists.each do |list| %>
		<div class="list-box col-md-3">
			<div class="list-box-contents">
				<p><strong><%= link_to list.title, list_path(list) %></strong></p>
				<p>
					<%= link_to edit_list_path(list) do %>
						<i class="fa fa-pencil fa-2" style="color:#B24700"></i>
					<% end %>
					&nbsp
					<%= link_to list_path(list), method: :delete, data: { confirm: "Are you sure?" } do %>
						<i class="fa fa-times fa-2" style="color:#FF6666"></i>
					<% end %>
				</p>
			</div>
		</div>
	<% end %>

	<div class="list-box col-md-3">	
	  <div class="new-list">
	  	<a href="lists/new"><button type="button" class="btn btn-lg btn-primary">+</button></a>
		</div>
	</div>

</div>

app/views/lists/new.html.erb
<h1>Create a New Goal</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1><br>

<div class="row border subgoals">
	<div class="subgoals-table">
		<%= form_tag complete_list_goals_path(@list), method: :put do %> 
			<table class="table">

				<thead>
					<th>Subgoal</th>
					<th colspan="2"></th>
				</thead>

				<% @list.goals.where(done: false).each do |goal| %>
					<tr>
						<td><%= goal.content %></td>
            <td><%= check_box_tag 'goal_ids[]', goal.id %></td>	
            <td>
							<%= link_to list_goal_path(@list, goal), method: :delete do %>
								<i class="fa fa-times fa-2" style="color:#FF6666"></i>
							<% end %> 
						</td>         
					</tr>
				<% end %>
			</table>

			<%= if @list.goals.where(done: false).any? then submit_tag "Mark as complete" end %>
	  <% end %>
	</div>
</div>

<br>

<div class="row border subgoals">
		<div class="subgoals-table">
			<table class="table">

				<thead>
					<th>Completed</th>
				</thead>

				<% @list.goals.where(done: :true).each do |goal| %>
					<tr>
						<td><%= goal.content %></td>             
					
						<td>
							<%= link_to list_goal_path(@list, goal), method: :delete do %>
								<i class="fa fa-times fa-2" style="color:#FF6666"></i>
							<% end %> 
						</td> 
					</tr>
				<% end %>

			</table>
		</div>
	</div>

<br>

<div class="row" style:"text-align:center">
	<h4>Add a new subgoal:</h4>

	<%= form_for [@list, @list.goals.build] do |f| %>	
		<p>
			<%= f.text_field :content %>
		</p>
		<p>
			<%= f.submit "Create Subgoal" %>
		</p>
	<% end %>
</div>

<br>

<%= link_to "Back", lists_path %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<nav>
    <ul>
      <li><i class="fa fa-copyright"></i>&nbsp Luc Sinex 2015</li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">		
	<nav>
		<div class="navbar-header">
			<div class="navbar-brand">
				<a href="/" class="logo">TOODOO</a>
			</div>
			<div class="header-links">
				<% if current_user %>
					<%= link_to "Goals", lists_path %> | 
					<%= link_to "Log out", logout_path %>
				<% else %>	
					<%= link_to "Sign Up", new_user_path %> | 
					<%= link_to "Log In", login_path %>
				<% end %>
			</div>
		</div>
	</nav>
</header>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to Toodoo!</h1><br>

<p>Toodoo is a simple to-do list app. Users can create an account and keep track of personal goals, which can be divided into subgoals. Have fun and enjoy being productive!</p>

<br>

<p>Toodoo was created by me, Luc Sinex, as a sample portfolio application. I am currently seeking employment as a web developer using Ruby on Rails. Please contact me at lucsinex at gmail dot com. Thanks!</p>

app/views/user_sessions/_form.html.erb
<%= form_for @user_session do |f| %>
  <div class="form_field">
  	<%= f.label :login %>
  	<%= f.text_field :login %>
  </div>
  <div class="form_field">
  	<%= f.label :password %>
  	<%= f.password_field :password %>
  </div>  
  <div class="form_field">
  	<%= f.submit "Submit" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Log In</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form_field">
  	<%= f.label :login %>
  	<%= f.text_field :login %>
  </div>
  <div class="form_field">
  	<%= f.label :email %>
  	<%= f.text_field :email %>
  </div>
  <div class="form_field">
  	<%= f.label :password %>
  	<%= f.password_field :password %>
  </div>
  <div class="form_field">
  	<%= f.label :password_confirmation %>
  	<%= f.password_field :password_confirmation %>
  </div>
  
  <div class="form_field">
  	<%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<%= render 'form' %>